
import { Shop } from './types';

export const shops: Shop[] = [
  {
    id: "1",
    name: "Fashion Boutique",
    description: "High-end fashion boutique offering the latest trends and designer pieces.",
    logo: "https://example.com/logos/fashionboutique.png",
    cover_image: "https://example.com/covers/fashionboutique.jpg",
    address: "123 Fashion Street, Style City, SC 12345",
    is_verified: true,
    shop_id: "fashion-boutique",
    owner_name: "Emma Styles",
    owner_email: "emma@fashionboutique.com",
    status: "active",
    password: "password123",
    phone_number: "+1234567890",
    rating: 4.8,
    review_count: 234,
    followers_count: 1250,
    created_at: "2023-01-15T12:00:00Z",
    productIds: ["p1", "p2", "p3", "p5", "p9"]
  },
  {
    id: "2",
    name: "Tech Haven",
    description: "Your one-stop shop for all tech gadgets and accessories.",
    logo: "https://example.com/logos/techhaven.png",
    cover_image: "https://example.com/covers/techhaven.jpg",
    address: "456 Tech Avenue, Digital City, DC 67890",
    is_verified: true,
    shop_id: "tech-haven",
    owner_name: "Alex Gadget",
    owner_email: "alex@techhaven.com",
    status: "active",
    password: "password123",
    phone_number: "+1987654321",
    rating: 4.6,
    review_count: 178,
    followers_count: 980,
    created_at: "2023-02-20T12:00:00Z",
    productIds: ["p8", "p11"]
  },
  {
    id: "3",
    name: "Organic Delights",
    description: "Fresh, organic produce and natural health products.",
    logo: "https://example.com/logos/organicdelights.png",
    cover_image: "https://example.com/covers/organicdelights.jpg",
    address: "789 Nature Road, Green Valley, GV 54321",
    is_verified: false,
    shop_id: "organic-delights",
    owner_name: "Olivia Green",
    owner_email: "olivia@organicdelights.com",
    status: "pending",
    password: "password123",
    phone_number: "+1567890123",
    rating: 4.9,
    review_count: 92,
    followers_count: 450,
    created_at: "2023-03-10T12:00:00Z",
    productIds: []
  }
];
